//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::events::Entity as Events;
pub use super::projects::Entity as Projects;
pub use super::user_auths::Entity as UserAuths;
pub use super::users::Entity as Users;
